services:
  bookshelf:
    build: .
    image: bookshelf:1.5.5
    container_name: bookshelf
    restart: unless-stopped
    ports:
      - "8090:5000"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
